### ISSUE TITLE
run data_reduce.py on Windows as standalone script

### ISSUE THREAD

**Issue by bmffb** [marfrh/osm-map-generator#2]
I would like to run the 
```
data_reduce.py
``` 
script as part of my own map creation process on a Windows PC. Is it possible (python 3 and the necessary packages are loaded)?
How would I start the script from a batch file? The respective tagmapping and theme files are placed in the same directory as the data_reduce.py file itself.

**Comment by marfrh** [comment]
In Theory, you can create a self-executable Python Script (ee one of the utilities e.g. `print_osm_object.py` as example) and run it from your bash script. Though as mentioned on the Readme, I can not verify whether the required tools work correctly on Windows Systems. Good luck!
